# Generated by Django 3.2 on 2021-04-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
